import Navbar1 from "@/components/UI/Navbar1";
import "./globals.css";

import {Space_Grotesk} from "next/font/google"
import Footer from "@/components/UI/Footer";

const spaceGrotesk = Space_Grotesk({
    subsets: ['latin'],
    variable: '--font-space-grotesk'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable}`}>
        <Navbar1 />
        {children}
        <Footer />
      </body>
    </html>
  );
}
